using SBESharp.Roslyn.Ir;

namespace SBESharp.Generator.Tests;

public sealed class SourceFormatterTests
{
	[Fact]
	public void Emit_OutputStartsWithAutoGeneratedMarker()
	{
		string source = SourceFormatter.GenerateSourceFiles(EmptySchema());

		Assert.StartsWith("// <auto-generated/>", source);
	}

	[Fact]
	public void Emit_ContainsCorrectNamespace()
	{
		string source = SourceFormatter.GenerateSourceFiles(EmptySchema("My.Cool.Ns"));

		Assert.Contains("namespace My.Cool.Ns", source);
	}

	[Fact]
	public void Emit_EmptyPackage_FallsBackToDefaultNamespace()
	{
		string source = SourceFormatter.GenerateSourceFiles(EmptySchema(string.Empty));

		Assert.Contains("namespace SBESharp.Generated", source);
	}

	[Fact]
	public void Emit_Enum_ProducesCSharpEnum()
	{
		SbeEnumDefinition gear = new SbeEnumDefinition(
			"Gear",
			SbePrimitive.U8,
			[new SbeEnumDefinition.ValidValue("Park", 0, null), new SbeEnumDefinition.ValidValue("Drive", 1, null)],
			Description: null);

		SbeSchema schema = EmptySchema() with { Types = [gear] };
		string source = SourceFormatter.GenerateSourceFiles(schema);

		Assert.Contains("public enum Gear : byte", source);
		Assert.Contains("Park = 0,", source);
		Assert.Contains("Drive = 1,", source);
	}

	[Fact]
	public void Emit_Enum_Uint16UnderlyingType()
	{
		SbeEnumDefinition en = new SbeEnumDefinition(
			"Status",
			SbePrimitive.U16,
			[new SbeEnumDefinition.ValidValue("Active", 1, null)],
			Description: null);

		SbeSchema schema = EmptySchema() with { Types = [en] };
		string source = SourceFormatter.GenerateSourceFiles(schema);

		Assert.Contains("public enum Status : ushort", source);
	}

	[Fact]
	public void Emit_Set_ProducesFlagsEnum()
	{
		SbeSet flags = new SbeSet(
			"DeviceFlags",
			SbePrimitive.U8,
			[new SbeSet.Choice("IsEnabled", 0, null), new SbeSet.Choice("IsPrimary", 1, null)],
			Description: null);

		SbeSchema schema = EmptySchema() with { Types = [flags] };
		string source = SourceFormatter.GenerateSourceFiles(schema);

		Assert.Contains("[Flags]", source);
		Assert.Contains("public enum DeviceFlags : byte", source);
		Assert.Contains("None = 0,", source);
		Assert.Contains("IsEnabled = 1 << 0,", source);
		Assert.Contains("IsPrimary = 1 << 1,", source);
	}

	[Fact]
	public void Emit_Message_ProducesFixedBlock()
	{
		SbeMessage message = new SbeMessage(
			"Reading",
			Id: 1,
			BlockLength: 16,
			Description: null,
			Fields: [Field("DeviceId", "int64"), Field("Value", "double", id: 2)],
			Groups: [],
			DataFields: []);

		string source = SourceFormatter.GenerateSourceFiles(SchemaWithMessage(message));

		Assert.Contains("[StructLayout(LayoutKind.Explicit, Pack = 1)]", source);
		Assert.Contains("internal struct ReadingFixedBlock", source);
		Assert.Contains("[FieldOffset(0)]", source);
		Assert.Contains("[FieldOffset(8)]", source);
		Assert.Contains("public long DeviceId;", source);
		Assert.Contains("public double Value;", source);
	}

	[Fact]
	public void Emit_Message_ProducesMessageStruct()
	{
		SbeMessage message = new SbeMessage(
			"Reading",
			Id: 1,
			BlockLength: 8,
			Description: null,
			Fields: [Field("DeviceId", "int64")],
			Groups: [],
			DataFields: []);

		string source = SourceFormatter.GenerateSourceFiles(SchemaWithMessage(message));

		Assert.Contains("public struct Reading", source);
		Assert.Contains("ISbeDeserializable<Reading>", source);
		Assert.Contains("public const ushort TemplateId = 1;", source);
		Assert.Contains("public static Reading Deserialize(", source);
		Assert.Contains("MemoryMarshal.Read<ReadingFixedBlock>", source);
	}

	[Fact]
	public void Emit_BigEndianSchema_UsesBigEndianReaders()
	{
		SbeMessage message = new SbeMessage(
			"Msg",
			Id: 1,
			BlockLength: 4,
			Description: null,
			Fields: [Field("Value", "int32")],
			Groups: [],
			DataFields: []);

		SbeSchema schema = new SbeSchema("Test.Ns", 1, 0, ByteOrder.BigEndian, [], [message], null, null, null);
		string source = SourceFormatter.GenerateSourceFiles(schema);

		Assert.Contains("BinaryPrimitives.ReadInt32BigEndian", source);
	}

	[Fact]
	public void Emit_SingleByteField_DoesNotUseBinaryPrimitives()
	{
		SbeMessage message = new SbeMessage(
			"Msg",
			Id: 1,
			BlockLength: 1,
			Description: null,
			Fields: [Field("Tag", "uint8")],
			Groups: [],
			DataFields: []);

		string source = SourceFormatter.GenerateSourceFiles(SchemaWithMessage(message));

		// LE path: single-byte field is read via MemoryMarshal, not BinaryPrimitives
		Assert.Contains("MemoryMarshal.Read<MsgFixedBlock>", source);
		Assert.DoesNotContain("BinaryPrimitives.ReadByte", source);
	}

	[Fact]
	public void Emit_Message_ProducesEncoderRefStruct()
	{
		SbeMessage message = new SbeMessage(
			"Reading",
			Id: 1,
			BlockLength: 8,
			Description: null,
			Fields: [Field("DeviceId", "int64")],
			Groups: [],
			DataFields: []);

		string source = SourceFormatter.GenerateSourceFiles(SchemaWithMessage(message));

		Assert.Contains("public ref struct ReadingEncoder", source);
		Assert.Contains("public static ReadingEncoder Encode(", source);
		Assert.Contains("public ReadingEncoder SetDeviceId(long value)", source);
		Assert.Contains("BinaryPrimitives.WriteInt64LittleEndian", source);
	}

	[Fact]
	public void Emit_SequentialFieldOffsets_AreComputedCorrectly()
	{
		SbeMessage message = new SbeMessage(
			"Msg",
			Id: 1,
			BlockLength: 12,
			Description: null,
			Fields:
			[
				Field("A", "int32", id: 1),   // offset 0, size 4
				Field("B", "double", id: 2),  // offset 4, size 8
			],
			Groups: [],
			DataFields: []);

		string source = SourceFormatter.GenerateSourceFiles(SchemaWithMessage(message));

		// FixedBlock uses [FieldOffset(n)]
		Assert.Contains("[FieldOffset(0)]", source);
		Assert.Contains("[FieldOffset(4)]", source);

		// Encoder still uses _offset + n
		Assert.Contains("_offset + 0", source);
		Assert.Contains("_offset + 4", source);
	}

	[Fact]
	public void Emit_EnumField_AppearsInMessageStruct()
	{
		SbeEnumDefinition gear = new SbeEnumDefinition(
			"Gear",
			SbePrimitive.U8,
			[new SbeEnumDefinition.ValidValue("Park", 0, null)],
			Description: null);

		SbeMessage message = new SbeMessage(
			"StatusReport",
			Id: 1,
			BlockLength: 1,
			Description: null,
			Fields: [EnumField("Gear", "Gear", SbePrimitive.U8)],
			Groups: [],
			DataFields: []);

		string source = SourceFormatter.GenerateSourceFiles(SchemaWithMessage(message, types: [gear]));

		Assert.Contains("public Gear Gear;", source);
	}

	[Fact]
	public void Emit_Group_ProducesGroupEntryAndEncoder()
	{
		SbeGroup group = new SbeGroup(
			"Wheels",
			Id: 7,
			DimensionType: "groupSizeEncoding",
			BlockLength: null,
			Fields: [Field("WheelId", "int32")],
			Groups: [],
			DataFields: [],
			Description: null);

		SbeMessage message = new SbeMessage(
			"Scan",
			Id: 1,
			BlockLength: 0,
			Description: null,
			Fields: [],
			Groups: [group],
			DataFields: []);

		string source = SourceFormatter.GenerateSourceFiles(SchemaWithMessage(message));

		Assert.Contains("public struct ScanWheelsEntry", source);
		Assert.Contains("public ref struct Scan", source);
		Assert.Contains("public ref struct ScanWheelsGroupEncoder", source);
		Assert.Contains("public SbeGroupView<ScanWheelsEntry> Wheels;", source);
		Assert.Contains("ParseWheelsGroup", source);
		Assert.Contains("MemoryMarshal.GetReference", source);
	}

	[Fact]
	public void Emit_BigEndianSchema_UsesBigEndianWriters()
	{
		// Arrange
		SbeMessage message = new SbeMessage(
			"Msg",
			Id: 1,
			BlockLength: 4,
			Description: null,
			Fields: [Field("Value", "int32")],
			Groups: [],
			DataFields: []);

		SbeSchema schema = BigEndianSchemaWithMessage(message);

		// Act
		string source = SourceFormatter.GenerateSourceFiles(schema);

		// Assert
		Assert.Contains("BinaryPrimitives.WriteInt32BigEndian", source);
	}

	[Fact]
	public void Emit_BigEndianSchema_DoesNotEmitFixedBlock()
	{
		// Arrange
		SbeMessage message = new SbeMessage(
			"Msg",
			Id: 1,
			BlockLength: 8,
			Description: null,
			Fields: [Field("Value", "int64")],
			Groups: [],
			DataFields: []);

		SbeSchema schema = BigEndianSchemaWithMessage(message);

		// Act
		string source = SourceFormatter.GenerateSourceFiles(schema);

		// Assert
		Assert.DoesNotContain("MsgFixedBlock", source);
		Assert.Contains("BinaryPrimitives.ReadInt64BigEndian", source);
	}

	[Fact]
	public void Emit_BigEndianGroup_UsesBigEndianGroupHeader()
	{
		// Arrange
		SbeGroup group = new SbeGroup(
			"Wheels",
			Id: 7,
			DimensionType: "groupSizeEncoding",
			BlockLength: null,
			Fields: [Field("WheelId", "int32")],
			Groups: [],
			DataFields: [],
			Description: null);

		SbeMessage message = new SbeMessage(
			"Scan",
			Id: 1,
			BlockLength: 0,
			Description: null,
			Fields: [],
			Groups: [group],
			DataFields: []);

		SbeSchema schema = BigEndianSchemaWithMessage(message);

		// Act
		string source = SourceFormatter.GenerateSourceFiles(schema);

		// Assert — group header must use BigEndian, not LittleEndian
		Assert.Contains("WriteUInt16BigEndian", source);
		Assert.Contains("ReadUInt16BigEndian", source);
		Assert.DoesNotContain("LittleEndian", source);
	}

	[Fact]
	public void Emit_BigEndianGroup_ParseReturnsArray()
	{
		// Arrange
		SbeGroup group = new SbeGroup(
			"Wheels",
			Id: 7,
			DimensionType: "groupSizeEncoding",
			BlockLength: null,
			Fields: [Field("WheelId", "int32")],
			Groups: [],
			DataFields: [],
			Description: null);

		SbeMessage message = new SbeMessage(
			"Scan",
			Id: 1,
			BlockLength: 0,
			Description: null,
			Fields: [],
			Groups: [group],
			DataFields: []);

		SbeSchema schema = BigEndianSchemaWithMessage(message);

		// Act
		string source = SourceFormatter.GenerateSourceFiles(schema);

		// Assert — BE groups return arrays, not SbeGroupView
		Assert.Contains("ScanWheelsEntry[]", source);
		Assert.DoesNotContain("SbeGroupView", source);
	}

	private static SbeSchema EmptySchema(string package = "Test.Ns") =>
		new SbeSchema(
			package,
			Id: 1,
			Version: 0,
			ByteOrder.LittleEndian,
			Types: [],
			Messages: [],
			Description: null,
			SemanticVersion: null,
			HeaderType: null);

	private static SbeSchema SchemaWithMessage(SbeMessage message, IReadOnlyList<SbeTypeDefinition>? types = null) =>
		new SbeSchema(
			"Test.Ns",
			Id: 1,
			Version: 0,
			ByteOrder.LittleEndian,
			Types: types ?? [],
			Messages: [message],
			Description: null,
			SemanticVersion: null,
			HeaderType: null);

	private static SbeSchema BigEndianSchemaWithMessage(SbeMessage message, IReadOnlyList<SbeTypeDefinition>? types = null) =>
		new SbeSchema(
			"Test.Ns",
			Id: 1,
			Version: 0,
			ByteOrder.BigEndian,
			Types: types ?? [],
			Messages: [message],
			Description: null,
			SemanticVersion: null,
			HeaderType: null);

	private static SbeField Field(string name, string type, ushort id = 1, string? desc = null)
	{
		var primitive = SbePrimitiveMap.TryParse(type, out var p) ? p : SbePrimitive.U8;
		return new SbeField(name, id, type, primitive, IsEnumOrSet: false, Offset: null, Presence.Required, desc);
	}

	private static SbeField EnumField(string name, string type, SbePrimitive primitive, ushort id = 1) =>
		new SbeField(name, id, type, primitive, IsEnumOrSet: true, Offset: null, Presence.Required, Description: null);
}
